### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by abartov** [ImanYZ/ExpertIdeasBot#2]
Could you take a moment to clarify the license under which you are sharing this code?  It would help enable re-use or contribution.

**Comment by ImanYZ** [comment]
Hi Asaf,

Thank you for your concern. I just added the license.

Best,
Iman

--
Iman YeckehZaare
Ph.D. Candidate
University of Michigan School of Information

[image: http://www.iman.one/] <http://www.iman.one/>   [image:
https://www.linkedin.com/in/oneweb/] <https://www.linkedin.com/in/oneweb/>
 [image: https://stackoverflow.com/users/2521204/iman]
<https://stackoverflow.com/users/2521204/iman>   [image:
https://en.wikipedia.org/wiki/User:I.yeckehzaare]
<https://en.wikipedia.org/wiki/User:I.yeckehzaare>   [image:
https://www.si.umich.edu/people/iman-yeckehzaare]
<https://www.si.umich.edu/people/iman-yeckehzaare>
